// export const generateSeed = async () => {
//   //dump data to file
//   const artists = await prismaClient.artist.findMany({})
//   fs.writeFileSync('./artists.json', JSON.stringify(artists))
// }

// import artists from "./artists.json";

// //use this to remove id, if you use an autogenerated ID
// const artistData = artists.map(({ id, ...rest }) => rest);

// //insert data to current db
// await prismaClient.artist.createMany({ data: artistData });

import fs from 'fs'

import { prisma } from '..'

const backupApps = async () => {
  const apps = await prisma.app.findMany()
  fs.writeFileSync('./apps.json', JSON.stringify(apps))
}

const backupBootVideos = async () => {
  const bootVideos = await prisma.bootVideo.findMany()
  fs.writeFileSync('./bootVideos.json', JSON.stringify(bootVideos))
}

backupApps()
backupBootVideos()
