// export const generateSeed = async () => {
//   //dump data to file
//   const artists = await prismaClient.artist.findMany({})
//   fs.writeFileSync('./artists.json', JSON.stringify(artists))
// }

// import artists from "./artists.json";

// //use this to remove id, if you use an autogenerated ID
// const artistData = artists.map(({ id, ...rest }) => rest);

// //insert data to current db
// await prismaClient.artist.createMany({ data: artistData });
import fs from 'fs'

import { prisma } from '..'

const seedApps = async () => {
  const appsJson = fs.readFileSync('./apps.json', { encoding: 'utf-8' })
  const apps = JSON.parse(appsJson)
  await prisma.app.createMany({ data: apps })
}

const seedBootVideos = async () => {
  const bootVideosJson = fs.readFileSync('./bootVideos.json', {
    encoding: 'utf-8',
  })
  const bootVideos = JSON.parse(bootVideosJson)
  await prisma.bootVideo.createMany({ data: bootVideos })
}

seedApps()
seedBootVideos()
