# name: Draft Release MacOSX

# on:
#   push:
#     tags:
#       - 'v*'
#   workflow_dispatch:

# env:
#   GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
#   GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
#   CSC_IDENTITY_AUTO_DISCOVERY: true
#   CSC_LINK: ${{ secrets.CSC_LINK }}
#   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
#   APPLE_ID: ${{ secrets.APPLE_ID }}
#   APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
#   TEAMID: ${{ secrets.TEAMID }}

# jobs:
#   draft-releases:
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - run: npm install -g yarn
#       - run: yarn
#       - run: yarn release:mac
