name: Draft Release Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  VITE_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.VITE_PUBLIC_SUPABASE_ANON_KEY }}
  VITE_PUBLIC_SUPABASE_URL: ${{ secrets.VITE_PUBLIC_SUPABASE_URL }}
  VITE_VERCEL_URL: ${{ secrets.VITE_VERCEL_URL }}
  NEXT_PUBLIC_STRIPE_PU: ${{ secrets.NEXT_PUBLIC_STRIPE_PU }}
  VITE_PUBLIC_STRIPE_PU: ${{ secrets.VITE_PUBLIC_STRIPE_PU }}

jobs:
  draft-releases:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools rpm snapcraft  make gcc g++ libx11-dev libxkbfile-dev fakeroot rpm
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: pnpm install

      - run: pnpm release:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_ID }}
