on:
  push:
    branches: [main]
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Flatpak Files'
        required: false

name: Flatpak-CI

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  VITE_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.VITE_PUBLIC_SUPABASE_ANON_KEY }}
  VITE_PUBLIC_SUPABASE_URL: ${{ secrets.VITE_PUBLIC_SUPABASE_URL }}
  VITE_VERCEL_URL: ${{ secrets.VITE_VERCEL_URL }}
  NEXT_PUBLIC_STRIPE_PU: ${{ secrets.NEXT_PUBLIC_STRIPE_PU }}
  VITE_PUBLIC_STRIPE_PU: ${{ secrets.VITE_PUBLIC_STRIPE_PU }}

jobs:
  flatpak:
    name: 'Flatpak Build'
    runs-on: ubuntu-latest
    # container:
    #   image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
    #   options: --privileged
    steps:
      - run: sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools rpm snapcraft  make gcc g++ libx11-dev libxkbfile-dev fakeroot rpm

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Install org.electronjs.Electron2.BaseApp
        run: flatpak install --noninteractive flathub org.electronjs.Electron2.BaseApp//22.08

      - name: Install org.freedesktop.Sdk.Extension.node18
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.node18//22.08

      - name: Install org.freedesktop.Sdk.Compat.i386/x86_64/22.08
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Compat.i386/x86_64/22.08

      - name: Install org.freedesktop.Sdk.Extension.toolchain-i386/x86_64/22.08
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.toolchain-i386/x86_64/22.08

      - name: Build artifacts.
        run: pnpm dist:flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AppImage.
        uses: actions/upload-artifact@v3
        with:
          name: linux-appimage
          path: apps/desktop/dist/Revealed-*.AppImage
          retention-days: 14

      # - name: Build Flatpak
      #   uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      #   with:
      #     bundle: revealed.flatpak
      #     manifest-path: flatpak-build/com.bunnystrike.revealed.yml
      #     cache-key: flatpak-builder-${{ github.sha }}
